### PR TITLE
Fix tests, add shrinkwrap and small additions for WildFly 10

### PR DESCRIPTION
**Pull request by sanderst**
Dependency versions have not been updated

### CODE REVIEW

**Comment by arcivanov** [comment]
@sanderst a few questions if you don't mind.

1. Why is shrinkwrap bundled with patch?
2. Why do you think that the OSGI "domain mode working as expected"? Or, to clarify, what is "expected"? The bundle management (start/stop) with management API is definitely still inoperable after this patch. So I'd like to know what the expectations are.

**Comment by sanderst** [comment]
1. It does not seem to be included in WF10 anymore and it will fail without it, possibly it could be made test-only?
2. We deploy to server groups and on enabling/disabling the deployments, the bundles are started/stopped properly
On disabling deployment:
<cut OSGi bundle logger stop messages>
2016-04-15 11:59:05,566 INFO  [org.jboss.osgi.framework] (MSC service thread 1-4) JBOSGI011003: Bundle stopped: srs-...-bundle:2.1.11
2016-04-15 11:59:05,576 INFO  [org.jboss.osgi.framework] (MSC service thread 1-1) JBOSGI011005: Bundle uninstalled: srs-...-bundle:2.1.11
2016-04-15 11:59:05,578 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0028: Stopped deployment srs-...-bundle.2c5b94d1891d (runtime-name: srs-...-bundle.jar) in 862ms
2016-04-15 11:59:06,241 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 115) WFLYSRV0009: Undeployed "srs-...-bundle.2c5b94d1891d" (runtime-name: "srs-...-bundle.jar")


On enabling deployment:
2016-04-15 11:59:59,750 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0027: Starting deployment of "srs-...-bundle.2c5b94d1891d" (runtime-name: "srs-....jar")
2016-04-15 11:59:59,775 INFO  [org.jboss.osgi.framework] (MSC service thread 1-4) JBOSGI011001: Bundle installed: srs-...-bundle:2.1.11
<cut OSGi bundle logger start messages>
2016-04-15 12:00:00,964 INFO  [org.jboss.osgi.framework] (MSC service thread 1-3) JBOSGI011002: Bundle started: srs-...-bundle:2.1.11
2016-04-15 12:00:00,974 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 117) WFLYSRV0010: Deployed "srs-...-bundle.2c5b94d1891d" (runtime-name : "srs-...-bundle.jar")

**Comment by arcivanov** [comment]
Thanks. 

I'll take a look at how Shinkwrap behaves in 10 and why it fails (I have reports that the current version works on 10 as well out of the box).

Ah. Well, I can tell you right away that that's not really a "domain support". JBOSGI is not domain-aware and deploys bundles on each domain member as if it was a standalone. There isn't an ability to stop the bundle on all the members of the group. The uninstallation will only happen on undeployment and stop on server stop and CLI still won't work at all. Glad we cleared that up.

I'll work on 10 this weekend. Cheers and thanks again!

**Comment by sanderst** [comment]
Thanks would be great.

While I had noticed that the old system of domain support in osgi was
missing as of WF8 it did not matter too much for our use case.

**Comment by arcivanov** [comment]
Thanks for the fix! I have merged it with your commit info under #16

**Pull request closed without merging**
