### PR TITLE
JBOSGI-792 Initial bundles fail to resolve if runtime name differs

### PR DESCRIPTION
**Pull request by sstoel**
Fix for initial bundles fail to resolve if runtime name differs

### CODE REVIEW

**Comment by arcivanov** [comment]
Could you do me a favor and squash?

**Comment by sstoel** [comment]
I'm sorry I tried but I never really use git (mercurial instead) and I
really have no idea how to do this, it's squashing all the wrong commits.

**Comment by arcivanov** [comment]
`git checkout JBOSGI-792`
`git rebase -i HEAD~2`

In the editor there's going to be two lines:
```
pick ...
pick ...
```

Replace the second `pick` with `fix`. Save. Push-force branch JBOSGI-792.

**Comment by arcivanov** [comment]
Awesome, thanks!

**Comment by arcivanov** [comment]
Ugh, sorry, I just looked at your commit. Please rebase it on latest master to remove all the pom changes.

```
git checkout master
git pull upstream master
git push
git checkout JBOSGI-792
git rebase master
git push -f
```

**Comment by sstoel** [comment]
It's getting worse and worse, nearly want to just throw away the fork and
just commit it in there... I really need to read up on using git, that
doesn't work either, merge conflict on the pull

**Comment by arcivanov** [comment]
Nevermind, I'll simply extract your change and change the authorship to you.
Check out the [gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/) doc.

**Comment by arcivanov** [comment]
Thanks for the commit. Merged. Closing.

**Pull request closed without merging**
